[env:esp32-c3-super-mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.partitions = default.csv

[env:wifi-diagnostic]
extends = env:esp32-c3-super-mini
build_flags = -D R2_WIFI_DIAGNOSTIC=1
