#pragma once

const char WEB_UI[] PROGMEM = R"HTML(
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>R2 Rapid Fire</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif}body{margin:0;background:#0c1118;color:#e9eef5}.wrap{max-width:760px;margin:auto;padding:20px}.card{background:#151d28;border:1px solid #293649;border-radius:14px;padding:18px;margin:14px 0}h1{font-size:25px;margin:6px 0}h2{font-size:16px;color:#9fb0c5}.status{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.stat{background:#0e151e;padding:12px;border-radius:10px}.stat b{display:block;font-size:20px;color:#52d3ff}.modes,.row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}button{border:0;border-radius:9px;padding:11px 15px;background:#29384c;color:white;font-weight:700}button.on{background:#e59822}.danger{background:#9d3434}label{display:grid;grid-template-columns:160px 1fr 58px;gap:10px;width:100%;align-items:center;margin:13px 0}input[type=range]{width:100%}.cal{background:#23734c}.note{color:#91a2b7;font-size:13px}.ok{color:#58df98}@media(max-width:550px){.status{grid-template-columns:1fr}label{grid-template-columns:110px 1fr 48px}}
</style></head><body><div class="wrap"><h1>R2 Rapid Fire</h1><div class="note">Firmware <b id="version">—</b> · <b>192.168.4.1</b></div>
<div class="card status"><div class="stat">Mode<b id="mode">—</b></div><div class="stat">R2 travel<b id="travel">—</b></div><div class="stat">ADC<b id="adc">—</b></div></div>
<div class="card"><h2>FIRE MODE</h2><div class="modes"><button onclick="cmd('/api/mode?value=off')">OFF</button><button onclick="cmd('/api/mode?value=continuous')">CONTINUOUS</button><button onclick="cmd('/api/mode?value=burst')">BURST</button></div>
<label>Continuous SPS<input id="sps" type="range" min="1" max="40"><output id="spsO"></output></label><label>Burst SPS<input id="burstSps" type="range" min="1" max="12"><output id="burstSpsO"></output></label><label>Burst shots<input id="burst" type="range" min="1" max="10"><output id="burstO"></output></label><label>Pulse width<input id="pulse" type="range" min="5" max="200"><output id="pulseO"></output></label><p class="note">Start burst mode at 8 SPS. A game may ignore pulses faster than the selected weapon can fire.</p></div>
<div class="card"><h2>TRIGGER</h2><label>Press point<input id="point" type="range" min="5" max="100"><output id="pointO"></output></label><label>Hysteresis<input id="hyst" type="range" min="0" max="30"><output id="hystO"></output></label><label>Debounce<input id="deb" type="range" min="0" max="500"><output id="debO"></output></label>
<div class="row"><button class="cal" onclick="cmd('/api/cal/released')">Capture released</button><button class="cal" onclick="cmd('/api/cal/pressed')">Capture pressed</button><button class="cal" onclick="cmd('/api/cal/apply')">Apply calibration</button></div><p id="cal" class="note"></p></div>
<div class="card"><h2>POWER</h2><label>Auto-sleep<input id="sleep" type="range" min="0" max="30"><output id="sleepO"></output></label><p class="note">0 disables sleep. Pull R2 to wake; the first pull is used for waking.</p><div class="row"><button onclick="cmd('/api/sleep')">Sleep now</button><button onclick="cmd('/api/reset-trigger')">Reset trigger</button><button class="danger" onclick="cmd('/api/defaults')">Restore defaults</button></div><p class="note">OFF always leaves GPIO0 as a high-impedance input.</p></div>
<div class="card"><h2>WIRELESS UPDATE</h2><input id="fw" type="file" accept=".bin"><button onclick="uploadFirmware()">Install update</button><p class="note">Use only a file ending in <b>-ota.bin</b>. Keep the controller powered until it reboots.</p></div><p id="msg" class="ok"></p></div>
<script>const $=id=>document.getElementById(id);let lock=0;async function cmd(url){try{let r=await fetch(url,{method:'POST'}),j=await r.json();$('msg').textContent=j.message||'Saved';lock=Date.now()+800}catch(e){$('msg').textContent='Request failed'}}async function uploadFirmware(){let f=$('fw').files[0];if(!f||!f.name.endsWith('-ota.bin')){$('msg').textContent='Choose the -ota.bin file';return}let b=new FormData();b.append('firmware',f);$('msg').textContent='Uploading—do not remove power';try{let r=await fetch('/api/update',{method:'POST',body:b}),j=await r.json();$('msg').textContent=j.message}catch(e){$('msg').textContent='Update connection closed; wait for reboot'}}function slider(id,url,suffix=''){let e=$(id),o=$(id+'O');e.oninput=()=>o.value=e.value+(e.value==0&&id==='sleep'?' (off)':suffix);e.onchange=()=>cmd(url+e.value)}slider('sps','/api/set?sps=');slider('burstSps','/api/set?burstSps=');slider('burst','/api/set?burst=');slider('pulse','/api/set?pulse=',' ms');slider('point','/api/set?point=','%');slider('hyst','/api/set?hyst=','%');slider('deb','/api/set?debounce=',' ms');slider('sleep','/api/set?sleep=',' min');async function poll(){try{let d=await(await fetch('/api/status')).json();$('version').textContent='v'+d.version;$('mode').textContent=d.mode.toUpperCase();$('travel').textContent=d.travel+'%';$('adc').textContent=d.adc;if(Date.now()>lock){for(let k of ['sps','burstSps','burst','pulse','point','hyst','deb','sleep']){$(k).value=d[k];$(k).oninput()}}$('cal').textContent=`Released ${d.released} · Pressed ${d.pressed} · ${d.polarity}`}catch(e){}setTimeout(poll,400)}poll();</script></body></html>
)HTML";
